# Generated by Django 4.1.7 on 2024-06-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekhoapp', '0002_carlist_chassisnumber_carlist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('service', models.TextField()),
            ],
        ),
    ]
