# Generated by Django 4.1.7 on 2024-06-06 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardekhoapp', '0003_showroomlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showroom', to='cardekhoapp.showroomlist'),
        ),
        migrations.AlterField(
            model_name='showroomlist',
            name='service',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='showroomlist',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
